"""creat tables Listing and Media

Revision ID: da7a5145f8de
Revises: 8b4a0425a4ec
Create Date: 2025-11-20 00:31:40.961180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7a5145f8de'
down_revision: Union[str, Sequence[str], None] = '8b4a0425a4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('original_photos', sa.String(), nullable=True))
    op.add_column('apartment', sa.Column('thumbnail_photos', sa.String(), nullable=True))
    op.add_column('apartment', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'created_at')
    op.drop_column('apartment', 'thumbnail_photos')
    op.drop_column('apartment', 'original_photos')
    # ### end Alembic commands ###
