"""drope table menia and listins, add cols type_property, rooms, floor, renovation

Revision ID: 9e61dd559fa2
Revises: 10b83d747837
Create Date: 2025-11-21 11:40:06.544447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e61dd559fa2'
down_revision: Union[str, Sequence[str], None] = '10b83d747837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('type_property', sa.String(), nullable=True))
    op.add_column('apartment', sa.Column('rooms', sa.Integer(), nullable=True))
    op.add_column('apartment', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('apartment', sa.Column('renovation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartment', 'renovation')
    op.drop_column('apartment', 'floor')
    op.drop_column('apartment', 'rooms')
    op.drop_column('apartment', 'type_property')
    # ### end Alembic commands ###
