"""creat stolb photos

Revision ID: e68aaefd5756
Revises: 8dacd53bee43
Create Date: 2025-11-20 01:41:21.985671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e68aaefd5756'
down_revision: Union[str, Sequence[str], None] = '8dacd53bee43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('photos', sa.String(), nullable=True))
    op.drop_column('apartment', 'created_at')
    op.drop_column('apartment', 'original_photos')
    op.drop_column('apartment', 'thumbnail_photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment', sa.Column('thumbnail_photos', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('apartment', sa.Column('original_photos', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('apartment', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('apartment', 'photos')
    # ### end Alembic commands ###
